trigger:
- develop

variables:
- group: SFDX_Vlocity_Variables

pool:
  vmImage: ubuntu-latest
#container: jfgarcia268/vlocity_sfdx:latest

stages:
  - stage: CCIDev1QADeployment
    displayName: Deployment to CCIDev1QA Org
    jobs:
      - deployment: SL_QA
        displayName: Deployment to Dev1QA
        environment: SL_QA
        timeoutInMinutes: 180
        container: jfgarcia268/vlocity_sfdx:latest
        variables:
          - name: deploy_url
            value: $(CCIDev1QA_SFDX_URL)
          - name: SF_USER
            value: CCIDEV1QA  
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: Deployment-template.yml
  - stage: CCIQADeployment
    displayName: Deployment to CCIQA Org
    jobs:
      - deployment: CCIQADeployment
        displayName: Deployment to CCIQA
        container: jfgarcia268/vlocity_sfdx:latest
        environment: CCIQA
        timeoutInMinutes: 180
        variables:
          - name: deploy_url
            value: $(CCIQA_SFDX_URL)
          - name: SF_USER
            value: CCIQA  
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - script: |
                    echo "Starting the Deployment to $(SF_USER) org"
                - template: Deployment-template.yml
