trigger:
- develop

variables:
- group: CSW_SFDX_Vlocity_Variables

pool:
  vmImage: ubuntu-latest
#container: jfgarcia268/vlocity_sfdx:latest

stages:
  - stage: CCIDevQADeployment
    displayName: Deployment to CCIDevQA Org
    jobs:
      - deployment: CCIDevQADeployment
        displayName: Deployment to QA
        environment: CCIDevQA
        timeoutInMinutes: 180
        container: jfgarcia268/vlocity_sfdx:latest
        variables:
          - name: deploy_url
            value: $(CCIDevQA)
          - name: SF_USER
            value: CCIDevQA  
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: Deployment-template.yml
